server:
  port: 8082
spring:
  application:
    name: pie-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        serviceName: ${spring.application.name} # 注册到consul的服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/pie?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:/db
    enabled: false
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS
#back datasource
pie:
  backup:
     datasource:
        host: 127.0.0.1
        userName: root
        password: root
        database: pie